services:
  app:
    container_name: nori-server
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    depends_on:
      - db
    expose:
      - 3000
  db:
    container_name: nori-server-db
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./.env
    expose:
      - 5432

  envoy:
    container_name: nori-server-api-gateway
    image: envoyproxy/envoy:v1.28.0
    volumes:
      - ./envoy/envoy.yml:/etc/envoy/envoy.yaml
    ports:
      - "9901:9901"
      - "8080:8080"
    depends_on:
      - app
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml", "--log-level", "info"]

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: nori-server-zookeeper
    restart: unless-stopped
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: nori-server-kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  postgres-data:

networks:
  dev_network:
    driver: bridge
