"""Init users, rooms, room_members, and messages tables

Revision ID: a6b6a2750ff6
Revises:
Create Date: 2025-02-08 13:18:51.753897

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a6b6a2750ff6"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "room_members", sa.Column("room_avatar_url", sa.TEXT(), nullable=True)
    )
    op.add_column(
        "room_members", sa.Column("user_avatar_url", sa.TEXT(), nullable=True)
    )
    op.drop_column("room_members", "room_avater_url")
    op.drop_column("room_members", "user_avater_url")
    op.add_column("rooms", sa.Column("avatar_url", sa.TEXT(), nullable=True))
    op.drop_column("rooms", "avater_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rooms", sa.Column("avater_url", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_column("rooms", "avatar_url")
    op.add_column(
        "room_members",
        sa.Column("user_avater_url", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "room_members",
        sa.Column("room_avater_url", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_column("room_members", "user_avatar_url")
    op.drop_column("room_members", "room_avatar_url")
    # ### end Alembic commands ###
