name: Pytest
on: [pull_request]
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
          cache: 'poetry'
      - name: Install protoc
        run: sudo apt install -y protobuf-compiler
      - name: Install dependencies
        run: poetry sync --extras dev
      - name: Setup .env
        run: cp .env.sample .env
      - name: Generate files from protos
        run: poetry run python scripts/generate.py
      - name: Test with pytest
        run: poetry run pytest
